### ISSUE TITLE
[ign] write a odom plugin for ign gazebo

### ISSUE THREAD

**Issue by kruusamae** [robotont/robotont_gazebo#30]
what is needed to write a odom plugin in ign gazebo

**Comment by FabianPG11** [comment]
In order to create our own plugin, I am following this tutorials:
[Create System Plugins](https://github.com/ignitionrobotics/ign-launch)
[Migration from Gazebo-classic: Plugins](https://ignitionrobotics.org/api/gazebo/3.2/migrationplugins.html)

and this repo:
https://github.com/ignitionrobotics/ign-launch

**Comment by FabianPG11** [comment]
Done, seems to be working fine.

**Comment by kruusamae** [comment]
540b72fd386d460040b5e1d254488a306b861471
