### ISSUE TITLE
figure out why different gazebo models rotate at different speeds

### ISSUE THREAD

**Issue by kruusamae** [robotont/robotont_gazebo#7]
@fabianPG11

**Comment by kruusamae** [comment]
see #6 for reference

**Comment by FabianPG11** [comment]
It seems that the problem is related with the values of inertia defined in the robotont_base model. There might be very low. 

Values for the camera:
`<inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />`

Values for robotont: 
`<inertia ixx="0.00002035985530754" ixy="0" ixz="0" iyy="0.00002035985530754" iyz="0" izz="0.00003945961663220"  />`

When we launch the model with the realsense model, the entire robot gets this inertia and that's why it can move normal. 
I tested launching the model robotont_gazebo_nuc.urdf  removing the inertia of the camera (putting the values as 0), and the robot moves slow, meaning that the inertia is the problem. 

As a test, if I increase the values of the inertia for the robot in robotont_base.urdf.xacro, It solves the problem.
